FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /exporter ./cmd/demo-exporter

FROM alpine:3.20
COPY --from=builder /exporter /exporter
EXPOSE 9099
ENTRYPOINT ["/exporter"]
